### ISSUE TITLE
Images are not rendered correctly

### ISSUE THREAD

**Issue by RyanBluth** [lily-mara/smol_egui_skia#1]
Images are rendered as the wrong color. Perhaps it's a color space issue, or the pixel format is mismatched?

## Example

**Input image:**

![image](https://github.com/lily-mara/smol_egui_skia/assets/5282031/48fe6006-9c8c-475e-8ce9-27973d27d9ad)

is rendered using the following code:

``` rust 
use egui::{include_image, CentralPanel};
use skia_safe::EncodedImageFormat;
use smol_egui_skia::{rasterize, RasterizeOptions};
use std::fs::File;
use std::io::Write;

pub fn main() {
    let mut surface = rasterize(
        (1024, 756),
        |ctx| {
            egui_extras::install_image_loaders(&ctx);
            CentralPanel::default().show(&ctx, |ui| {
                ui.image(include_image!("../ferris.jpg"));
            });
        },
        Some(RasterizeOptions {
            pixels_per_point: 1.0,
            frames_before_screenshot: 20,
        }),
    );

    let data = surface
        .image_snapshot()
        .encode_to_data(EncodedImageFormat::PNG)
        .expect("Failed to encode image");

    File::create("output.png")
        .unwrap()
        .write_all(&data)
        .unwrap();

    println!("wrote output.png");
}
```

**Dependencies:**
``` toml
egui = "0.27.2"
skia-safe = "0.73.0"
smol_egui_skia = "0.1.1"
egui_extras = { version = "0.27.2", features = ["all_loaders"] }
image = { version = "0.24", features = ["png", "jpeg"] }
```

**Output image:**
![image](https://github.com/lily-mara/smol_egui_skia/assets/5282031/65a907ce-49f9-490e-b6f6-8818c24ae03b)
